config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Bookmarks
  resources :bookmarks, only: [:create, :destroy]

  resources :lists do
    resources :bookmarks, only: [:create, :destroy]
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list}
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
  has_many :lists, through: :bookmarks
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    redirect_to @list
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Lists</h1>

  <ul class="list-group mb-4">
    <% @lists.each do |list| %>
      <li class="list-group-item">
        <%= link_to list.name, list, class: "text-decoration-none" %>
      </li>
    <% end %>
  </ul>

  <%= link_to 'New List', new_list_path, class: "btn btn-primary" %>
</div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= form_with(model: @list, url: lists_path) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit 'Create List' %>
  </div>
<% end %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<div class="container mt-5">
  <h1 class="mb-4"><%= @list.name %></h1>

  <h2>Movies in this list:</h2>
  <ul class="list-group mb-4">
    <% @list.bookmarks.each do |bookmark| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= bookmark.movie.title %>
        <%= link_to "Delete", list_bookmark_path(@list, bookmark), class: "btn btn-danger btn-sm", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      </li>
    <% end %>
  </ul>

  <h2>Add a new movie:</h2>
  <%= form_with(model: [@list, @bookmark], url: list_bookmarks_path(@list), class: "mb-4") do |form| %>

    <div class="mb-3">
      <%= form.label :movie_id, class: 'form-label' %>
      <%= form.collection_select :movie_id, Movie.all, :id, :title, {prompt: "Select a movie"}, {class: "form-select"} %>
    </div>

    <div class="mb-3">
      <%= form.label :comment, class: 'form-label' %>
      <%= form.text_field :comment, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= form.submit 'Add a movie', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <%= link_to 'Back', lists_path, class: "btn btn-secondary" %>
</div>